### ISSUE TITLE
Is this a full two-way sync?

### ISSUE THREAD

**Issue by Fabian42** [hschauhan/gosync#10]
I had bad experiences with RCloneSync and a lot of tools for Linux are only partially developed. Does this work like the official client on Windows? Does it properly sync all renames, deletes, file changes, etc. in both directions? Does it also keep working when I reboot while it's syncing?

**Comment by hschauhan** [comment]
I haven't gotten any chance to test it on Windows. Yes, its a two-way sync on Linuxes.
