### ISSUE TITLE
Google API instructions outdated

### ISSUE THREAD

**Issue by Fabian42** [hschauhan/gosync#11]
The linked tutorial (https://github.com/jay0lee/GAM/wiki/CreatingClientSecretsFile) is outdated. The design, layout and structure of the website was changed, so almost none of the buttons is the same anymore.

Also, other sync programs use authorisation via a simple link that the user can click, log in in the browser, then either paste back an authorisation code or just have it applied automatically. Why was a different approach chosen here?

**Comment by hschauhan** [comment]
The generation of Credential.json file is messy but we can't do anything about it. Once you have credentials file, then its pretty straight forward. Gosync opens a web browser for authentication.

**Comment by hschauhan** [comment]
I think latest video from Alan and his wiki explains the process well. Closing this problem.

**Comment by Fabian42** [comment]
Video? I wouldn't want to watch a video just to do the basic setup of a program. And many others don't want to, either. Can't you just type the steps?

**Comment by SGmuwa** [comment]
@Fabian42 
Try this: https://hschauhan.github.io/gosync/, Installation section,
or this: https://github.com/hschauhan/gosync#installation

**Comment by Fabian42** [comment]
The link was actually already updated to https://github.com/arentoine/gosync/wiki on the 14th of April, which contains the correct instructions. So yes, this issue is actually resolved, but for a different reason than what you said 8 or 2 days ago.
