### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by ppazos** [hschauhan/gosync#13]

**Comment by hschauhan** [comment]
Yes. There is some problem with the library this software depends on. Once that is fixed, I will resume the work. Did you have some query?

**Comment by ppazos** [comment]
@hschauhan no queries, just want to try the project and from the last updated dates it seemed unattended.

**Comment by cimdrap** [comment]
I would try it too

**Comment by smjure** [comment]
@hschauhan Is this code still alive and working in 2020? Seems to be a promising project.

**Comment by hschauhan** [comment]
Yes it is! We have just moved to Google API v3!

**Comment by hschauhan** [comment]
v0.5 is released now. But I would suggest that top of the tree (by cloning the repository) is used. It has gotten better than v0.5.
