### ISSUE TITLE
Doesn't sync subdirs

### ISSUE THREAD

**Issue by ungooglable** [hschauhan/gosync#14]
(Ubuntu Mate 18.04)

After initializing GoSYnc shows my Google Drive usage correctly, but then it syncs only files in GDrive's _root_. 

Settings page also shows all my dirs unchecked. See the screenshot. And they are disabled to check. Toggling 'Sync everything' box does nothing for that matter

![screenshot at 2019-02-05 21-05-54](https://user-images.githubusercontent.com/23142833/52298231-305b6600-298b-11e9-9ad8-806cefda3594.png)

**Comment by hschauhan** [comment]
Can you try the latest code from github? Nobody has reported such problem. I have been testing this is on multiple machines with lots of nested directories and files. But all this is tested on latest code from github.

**Comment by hschauhan** [comment]
From screenshot it looks like 0.4 version. Latest code in github doesn't has this problem. Please reopen this ticket if you still see the issue in latest code.
