### ISSUE TITLE
Request: Local target directory option

### ISSUE THREAD

**Issue by ungooglable** [hschauhan/gosync#15]
Please add some way to select local directory to sync. 

Use case: I have an HDD and an SSD. My SSD is for the system (and apps) only. All _my data_ stored on the HDD, so I can kill the SSD at will

**Comment by scottcoombes** [comment]
I have the exact same problem. Would be great if this could be added!
I don't have enough knowledge of python to try to update that myself.

**Comment by hschauhan** [comment]
Sure. Request taken!

**Comment by hschauhan** [comment]
Started work on it.

**Comment by hschauhan** [comment]
This is implemented in the latest code! Thanks for the request!
