### ISSUE TITLE
Installation opens wiki page filled with garbage

### ISSUE THREAD

**Issue by Fabian42** [hschauhan/gosync#16]
When I install it after following the fix in #12, I get this output:

```
fabian@debian-vm:~/.local/bin$ ./GoSync 
/home/fabian/.local/lib/python2.7/site-packages/GoSync/GoSync.py:30: wxPyDeprecationWarning: Using deprecated class PySimpleApp. 
  app = wx.PySimpleApp()
fabian@debian-vm:~/.local/bin$ Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[2600:2600:0206/154043.722748:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[2559:2580:0206/154043.850288:ERROR:browser_process_sub_thread.cc(209)] Waited 3 ms for network service
Opening in existing browser session.
```

Then a new Chrome tab opens with this page in it: https://github.com/jay0lee/GAM/wiki/Creating-client_secrets.json-and-oauth2service.json

The content of that wiki page is "uijlkhrh78jipcqij78atf89;jv23m9j8;lvpqm;l8v2pq3nm9v2p3qnj7pv32q78pv3aj7vatwfnpq23vlin678a2vw3f9aw2i3lkialpuh96;vapw3ikuj7bgq23y8h76q2b3gkiuj7q253hy8q23v4ki8qv276jq2345hiq8924jlqn;m398lmqwyu" and even the previous revisions don't tell me what I'm actually supposed to do, it's just a JSON file.

**Comment by hschauhan** [comment]
Please read the latest Readme. Alain has explained the installation very well!
