### ISSUE TITLE
failed to install through pip and source.

### ISSUE THREAD

**Issue by gauraputu** [hschauhan/gosync#19]
it gave the following error

> Collecting GoSync
  Downloading https://files.pythonhosted.org/packages/1b/f8/327098b3594b9a160a8e661eba2b0c98a1ebb71d1f3392f3b4ffe686eb82/GoSync-0.4-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 174kB/s 
Collecting pydrive (from GoSync)
  Downloading https://files.pythonhosted.org/packages/6b/2d/c8e052ba51099faee0bfe71d84f35bb1576e6910483cad46b840a122ca6c/PyDrive-1.3.1-py2-none-any.whl
Collecting watchdog (from GoSync)
  Downloading https://files.pythonhosted.org/packages/01/01/cc9b2fd111e19687dd42155f066718bccb414c8a728eb7df0b229742caf7/watchdog-0.10.0.tar.gz (94kB)
    100% |████████████████████████████████| 102kB 482kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
>   
>   ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-P_enxZ/watchdog/

and when I run setup.py from source it gave similar error

> Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by cserpell** [comment]
Maybe you are trying python3.

I would try two things:
1) `pip install setuptools` and run again.
2) If that doesn't work, see how to run python2.7 in your machine (not python3, if you are using that now).

**Comment by gauraputu** [comment]
thanks! it works now
