### ISSUE TITLE
Start in background

### ISSUE THREAD

**Issue by uggla** [hschauhan/gosync#2]
First of all, congratulation for your work, gosync is a good job !

I would like to add gosync into my session startup.
My expectations would be to have it :
- authenticate silently
- run in the background
- having a tray icon. A click on it would open the current gui.

My request is similar to #1, but keeping the gui for a more friendly desktop usage.

**Comment by hschauhan** [comment]
Thanks!

I had authenticate silently earlier. Its a simple thing to do. Running in background is a request I have from many people mainly server guys. I will see what can be done. Tray icon is problematic with wxPython. It doesn't work with Ubuntu.

**Comment by hschauhan** [comment]
Hi,

Tray icon has been added. And I have tested it on Ubuntu (Gnone, xfce) and Apple mac book. I have test it on KDE systems.

Authentication is not required now on every load. But first time you have to do authentication. So it can't be silent when running first time.

I a working on running it in background

All this will be available in 0.5

Could you please create separate issues for each of them?

**Comment by hschauhan** [comment]
The tray icon is a messy thing and doesn't work on all systems the same. We have done away with that. Silent authentication can't be supported. First time authentication has to be interactive. Post that the authentication is silent. Need to add daemon mode.
