### ISSUE TITLE
"Client secret file was not found . Do you want to know how to create one ?"

### ISSUE THREAD

**Issue by ghost** [hschauhan/gosync#24]
https://github.com/arentoine/gosync/wiki . I make all from this instruction . After i print GoSync in console and receive "Client secret file was not found . Do you want to know how to create one ?" . When i click "yes" it open Calibre, when "no" nothing happens. What needs to be done to make the program work?

**Comment by arentoine** [comment]
Hello,
to get the "Client Secret File" (lately renamed by Google to Credentials.json) you need to complete the steps under the section 2. of the Wiki :

2. Retrieve the file "Crendentials.json" (Enable Google Drive API)

    Goto to the Google Drive API (https://developers.google.com/drive/api/v3/quickstart/python)
    In the section “Step 1: Turn on the Drive API” : Click on the button “Enable the Drive API”.
    In the window “Configure you OAuth client” : keep selection “Desktop app” then click on “Create”
    In the window “You're all set!” : click on “Download Client Configuration”
    Save the file “Credentials.json” to a location of your choise.

Restart GoSync and it should as you to load the Credentials.json.

Keep me posted on the result of your journey, we'll update the Wiki accordingly.

Regards

**Comment by ghost** [comment]
I did this, but apparently I am loading this file in the wrong place. Maybe there is a certain place where the file should be?

**Comment by arentoine** [comment]
Hello,

let's start from scratch...

first, delete the config directory : rm ~/.gosync -r

second, make sure the "credentials.json" file is valid : open the file with a text editor and confirm it starts with something like : 
     {"installed":{"client_id":"XXXXXXXXX-XXXX ...

If not, recreate the file with the instructions in section 2 of the wiki.

Restart GoSync and click on Yes when GoSync ask you to load the Credentials file.  You will have to locate the file with the file chooser dialog.  It will then save the file to the right place.

I will create a youtube video to show how to go through these preliminary steps.

Again, keep me posted.

Regards  


we'll make it work, I'm sure... :-)

**Comment by ghost** [comment]
Hello,

first - yes, i delete
second - yes, i open and i am sure about it.
third - no, when i click "yes" in dialog window , it open Calibre a library tool. instead a 'locate the file with the file chooser dialog',
Maybe i have something wrong with Calibre ? 
Do not know a similar case and solution for it?

**Comment by arentoine** [comment]
Hello,

can you send me a screen shot of the dialog window on the above third step ?

Thanks !

**Comment by ghost** [comment]
![Screenshot_20200429_153718](https://user-images.githubusercontent.com/47359363/80596752-89e7fe80-8a2f-11ea-906c-9cdf6c497993.png)

**Comment by ghost** [comment]
> ![Screenshot_20200429_153718](https://user-images.githubusercontent.com/47359363/80596752-89e7fe80-8a2f-11ea-906c-9cdf6c497993.png)

when click yes it appears
![Screenshot_20200429_153842](https://user-images.githubusercontent.com/47359363/80596886-bf8ce780-8a2f-11ea-930e-315afc3d2b12.png)

**Comment by ghost** [comment]
Just now i delete calibre, and now when i click "yes' it redirect to https://github.com/jay0lee/GAM/wiki/Creating-client_secrets.json-and-oauth2service.json

**Comment by arentoine** [comment]
Hello again,

ahhhhh !  This looks an old version of GoSync.  Can you download the source again and complete section 3 of the wiki ?

**Comment by ghost** [comment]
> Just now i delete calibre, and now when i click "yes' it redirect to https://github.com/jay0lee/GAM/wiki/Creating-client_secrets.json-and-oauth2service.json

When i made all steps from link, programm , started to work.

**Comment by arentoine** [comment]
Excellent !

Have a nice day.

**Comment by ghost** [comment]
Have a nice day too
