### ISSUE TITLE
 how to start running (raspberry pi 3)

### ISSUE THREAD

**Issue by nicolasculma** [hschauhan/gosync#34]
so far everything works correctly but due to requirements I need to start the program as soon as it starts synchronizing, the problem is that I don't know what to modify so that when it starts it is not paused

**Comment by hschauhan** [comment]
Hi Nicolas,

When GoSync starts to run the very first time, it needs to know what all should be synced. People might have 100GB of data in Google Drive and may or may not want to sync it all.

Automatically start the sync can be done but when you run it the very first time, you would need to select the folders you want to sync or just select "sync all" from settings tab.

Note taken. The automatic sync start will be added.

**Comment by nicolasculma** [comment]
Yes, that initial configuration I already know, I already configured the raspberry pi so that it starts the program automatically when it is turned on but it does not synchronize until I click on it in summary, then I want to know what part of the code I can modify so that each time I start GoSync sync without clicking

**Comment by hschauhan** [comment]
Hi Nicolas,

There is a check box provided in settings. If that is checked, the sync will start automatically on app start.
