### ISSUE TITLE
KeyError: 'limit'

### ISSUE THREAD

**Issue by smjure** [hschauhan/gosync#41]
First of all thank you for reviving the project. I installed the GoSync successfully on Raspberry Pi 4B based on the YouTube link. Then when I run then the GoSync command as the last command, I get the following error:

`
Traceback (most recent call last):
  File "/usr/local/bin/GoSync", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/GoSync/GoSync.py", line 38, in main
    controller = GoSyncController()
  File "/usr/local/lib/python3.7/dist-packages/GoSync/GoSyncController.py", line 135, in __init__
    self.FileSizeHumanize(long(self.aboutdrive['storageQuota']['limit'])))
KeyError: 'limit'
`

It seems there is space limit, which is true for the partition where GoSync is installed. I want to actually point it to a NAS disk. How can I do that? Thanks in advance.

**Comment by hschauhan** [comment]
which version is it? Also can you try with latest code in github?

**Comment by hschauhan** [comment]
By the way, this limit has nothing to do with your Disk or Google drive limit. This is a code error. That's why I am asking to try latest code in github. Let me know if you want to know how to do it.

**Comment by smjure** [comment]
Thanks for the reply. I believe it's the latest version, have followed the steps from your wiki [youtube](https://www.youtube.com/watch?v=_FzLPgvzO1E&list=LLirF9VF53K8rGOYHf5PoQdQ&index=2&t=0s) video - the download is made via `git clone https...`.

Perhaps should mention that I try to link it with G Suite, but should not be a problem since I successfully use it with rclone.

**Comment by smjure** [comment]
FYI, have tried it also on my laptop with Linux Mint 19.3, the same error pops up.

**Comment by reece394** [comment]
I am having the same issue. Using GSuite for Business with unlimited cloud storage. It could be crashing due to expecting a storage limit on Google Drive but GSuite doesn't have one. Is it stored as a number by any chance? Was skimming the code and saw your use of long. Maybe Google Drive is returning Unlimited as a string?

**Comment by arentoine** [comment]
Hello smjure,

It took me some time to realize, as for The Matrix where "... there is no spoon!", that there is not limit in G Suite...   :-)

I pushed a fix where the limit is set to the current usage.

If you could test it and keep us posted ?

Regards

Alain

**Comment by reece394** [comment]
This has fixed the error. It no longer appears and allows Google Drive to be queried and I tested syncing some files and it works. Thanks for fixing it

**Comment by smjure** [comment]
Also myself tested it and it works great, flawlessly so far... very much appreciated!!
