### ISSUE TITLE
How do you start the program?

### ISSUE THREAD

**Issue by multiwebinc** [hschauhan/gosync#5]
Instructions only say how to install it, but not how to run it.

**Comment by bittner** [comment]
The `GoSync` Python package installs a program called ... :drum: :drum: :drum: ... `GoSync`. Just run that.

And yes, for completeness it would be a good idea to add that to the README.

**Comment by bittner** [comment]
Apologies. Just figured that ...

On Ubuntu (17.04 Zesty) the `GoSync` command is only available in your path when GoSync is installed from within a virtualenv. If you install it without a virtual environment the command is installed somewhere at `<site-packages>/../../../bin/`.

You can (or "have to") symlink it for your convenience somewhat like this:
```
$ realpath `python -m site --user-site`/../../../bin/GoSync
/home/<your-username>/.local/bin/GoSync
$ ln -sv $(realpath `python -m site --user-site`/../../../bin/GoSync) GoSync
'GoSync' -> '/home/<your-username>/.local/bin/GoSync'
$ ./GoSync
```

This could do with some improvements to make it end-user friendly, granted.

**Comment by hschauhan** [comment]
Hi bittner,

Thanks pointing to this problem. I would actually like to make a deb file for distribution but I am not sure how to. Would you know?

**Comment by bittner** [comment]
Creating a Debian package is not all that magic. You mainly create a control file and a collection of files you want to distribute.

References
------------

- https://wiki.debian.org/Packaging
- https://wiki.debian.org/HowToPackageForDebian
- https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html
- https://askubuntu.com/questions/1345/what-is-the-simplest-debian-packaging-guide
