### ISSUE TITLE
What does this (GoSync:2074): Gtk-CRITICAL  startup error message mean?

### ISSUE THREAD

**Issue by tomreedtoon** [hschauhan/gosync#63]
(GoSync:2074): Gtk-CRITICAL **: 11:03:11.268: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(GoSync:2074): Gtk-CRITICAL **: 11:03:11.268: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

This shows up whenever I start GoSync. It seems to be working...kind of...but does this indicate that there's a problem?

**Comment by hschauhan** [comment]
Sorry for a very late reply. But these messages are okay.
