### ISSUE TITLE
GoSync requests access permissions each time it starts

### ISSUE THREAD

**Issue by Flamekebab** [hschauhan/gosync#7]
This may be an issue with how I setup client_secrets.json or may be a GoSync issue. Given that there's very little guidance for that part of installation I don't know the cause.

I'm fairly sure GoSync has fully synced (it's really hard to tell - please make it clearer in 0.5!) but when I restart the computer it immediately pops up a browser window to request access to Google Drive. Every time. I'm fairly sure this used to be a problem but was fixed.

I'm running GoSync on Ubuntu 17.10 with the Pantheon desktop environment.

**Comment by ungooglable** [comment]
Same for me here
(except it doesn't sync subdirs)

GoSync 0.4 on Ubuntu 18.04 with Mate flavor

**Comment by arentoine** [comment]
Hello,

this should have been fixed with the current version of the source code available at GitHub.

GoSync now keeps a session active and will not request authentication after the initial start.

Keep us posted if this works for you.

Regards

**Comment by hschauhan** [comment]
This has been fixed. Closing the issue. If you find problem, please feel free to reopen!
